#!/bin/bash

SERVICE="ffmpeg"
Current_vid=$(ps aux | grep -i  ffmpeg | grep -i wmv | awk '{print $13}' | cut -b 18-)

if pgrep -x "$SERVICE" >/dev/null

then
    echo "FVS is running"
    echo "Video INP - ${Current_vid}"

else
    echo "FVS is not running"

fi
